forge "http://forge.puppetlabs.com"

mod 'apt', :git => 'git://github.com/puphpet/puppetlabs-apt.git'
mod 'elasticsearch/elasticsearch', '0.2.3'
mod 'java7', :git => 'https://github.com/Spantree/puppet-java7.git'
